services:
  mongo:
    image: mongo:6.0
    container_name: million-mongo
    restart: always
    ports:
      - "27027:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: million-backend
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDb=mongodb://mongo:27017
      - DatabaseSettings__DatabaseName=MillionDb
    ports:
      - "5000:8080"

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:5000
    container_name: million-frontend
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    ports:
      - "3000:3000"

volumes:
  mongo_data:
